name: wassncplot
channels:
  - conda-forge
  - defaults
dependencies:
  - blas=1.1
  - bzip2=1.0.6
  - ca-certificates=2019.3.9
  - cairo=1.14.12
  - certifi=2019.3.9
  - cftime=1.0.3.4
  - curl=7.64.0
  - ffmpeg=4.0.2
  - fontconfig=2.13.1
  - freetype=2.10.0
  - gettext=0.19.8.1
  - giflib=5.1.7
  - glib=2.56.2
  - gmp=6.1.2
  - gnutls=3.5.19
  - graphite2=1.3.13
  - harfbuzz=1.9.0
  - hdf4=4.2.13
  - hdf5=1.10.2
  - icu=58.2
  - jasper=1.900.1
  - jpeg=9c
  - krb5=1.16.3
  - lame=3.100
  - libblas=3.8.0
  - libcblas=3.8.0
  - libcurl=7.64.0
  - libcxx=4.0.1
  - libcxxabi=4.0.1
  - libedit=3.1.20170329
  - libffi=3.2.1
  - libgfortran=3.0.1
  - libiconv=1.15
  - liblapack=3.8.0
  - liblapacke=3.8.0
  - libnetcdf=4.6.1
  - libpng=1.6.36
  - libssh2=1.8.2
  - libtiff=4.0.10
  - libwebp=0.5.2
  - libxml2=2.9.8
  - ncurses=6.1
  - netcdf4=1.4.1
  - nettle=3.3
  - numpy=1.15.2
  - openblas=0.2.20
  - opencv=3.4.1
  - openh264=1.8.0
  - openssl=1.1.1b
  - pcre=8.41
  - pip=19.0.3
  - pixman=0.34.0
  - python=3.6.7
  - readline=7.0
  - scipy=1.1.0
  - setuptools=40.8.0
  - sqlite=3.26.0
  - tk=8.6.9
  - tqdm=4.31.1
  - vispy=0.5.3
  - wheel=0.33.1
  - x264=1!152.20180806
  - xz=5.2.4
  - zlib=1.2.11

